package com.example.converter.presentation.widget

import com.example.converter.R

fun getFlagDrawableId(currencyCode: String): Int {
    return when (currencyCode.uppercase()) {
        "AED" -> R.drawable.ae_flag
        "AFN" -> R.drawable.af_flag
        "ALL" -> R.drawable.al_flag
        "AMD" -> R.drawable.am_flag
        "AOA" -> R.drawable.ao_flag
        "ARS" -> R.drawable.ar_flag
        "AUD" -> R.drawable.au_flag
        "AWG" -> R.drawable.aw_flag
        "AZN" -> R.drawable.az_flag
        "BAM" -> R.drawable.ba_flag
        "BBD" -> R.drawable.bb_flag
        "BDT" -> R.drawable.bd_flag
        "BGN" -> R.drawable.bg_flag
        "BHD" -> R.drawable.bh_flag
        "BIF" -> R.drawable.bi_flag
        "BMD" -> R.drawable.bm_flag
        "BND" -> R.drawable.bn_flag
        "BOB" -> R.drawable.bo_flag
        "BRL" -> R.drawable.br_flag
        "BSD" -> R.drawable.bs_flag
        "BTN" -> R.drawable.bt_flag
        "BWP" -> R.drawable.bw_flag
        "BYN" -> R.drawable.by_flag
        "BZD" -> R.drawable.bz_flag
        "CAD" -> R.drawable.ca_flag
        "CDF" -> R.drawable.cd_flag
        "CHF" -> R.drawable.ch_flag
        "CLP" -> R.drawable.cl_flag
        "CNY" -> R.drawable.cn_flag
        "COP" -> R.drawable.co_flag
        "CRC" -> R.drawable.cr_flag
        "CUP" -> R.drawable.cu_flag
        "CVE" -> R.drawable.cv_flag
        "CZK" -> R.drawable.cz_flag
        "DJF" -> R.drawable.dj_flag
        "DKK" -> R.drawable.dk_flag
        "DOP" -> R.drawable.do_flag
        "DZD" -> R.drawable.dz_flag
        "EGP" -> R.drawable.eg_flag
        "ERN" -> R.drawable.er_flag
        "ETB" -> R.drawable.et_flag
        "EUR" -> R.drawable.eu_flag
        "FJD" -> R.drawable.fj_flag
        "FKP" -> R.drawable.fk_flag
        "GBP" -> R.drawable.gb_flag
        "GEL" -> R.drawable.ge_flag
        "GHS" -> R.drawable.gh_flag
        "GIP" -> R.drawable.gi_flag
        "GMD" -> R.drawable.gm_flag
        "GNF" -> R.drawable.gn_flag
        "GTQ" -> R.drawable.gt_flag
        "GYD" -> R.drawable.gy_flag
        "HKD" -> R.drawable.hk_flag
        "HNL" -> R.drawable.hn_flag
        "HRK" -> R.drawable.hr_flag
        "HTG" -> R.drawable.ht_flag
        "HUF" -> R.drawable.hu_flag
        "IDR" -> R.drawable.id_flag
        "ILS" -> R.drawable.il_flag
        "INR" -> R.drawable.in_flag
        "IQD" -> R.drawable.iq_flag
        "IRR" -> R.drawable.ir_flag
        "ISK" -> R.drawable.is_flag
        "JMD" -> R.drawable.jm_flag
        "JOD" -> R.drawable.jo_flag
        "JPY" -> R.drawable.jp_flag
        "KES" -> R.drawable.ke_flag
        "KGS" -> R.drawable.kg_flag
        "KHR" -> R.drawable.kh_flag
        "KMF" -> R.drawable.km_flag
        "KPW" -> R.drawable.kp_flag
        "KRW" -> R.drawable.kr_flag
        "KWD" -> R.drawable.kw_flag
        "KYD" -> R.drawable.ky_flag
        "KZT" -> R.drawable.kz_flag
        "LAK" -> R.drawable.la_flag
        "LBP" -> R.drawable.lb_flag
        "LKR" -> R.drawable.lk_flag
        "LRD" -> R.drawable.lr_flag
        "LSL" -> R.drawable.ls_flag
        "LYD" -> R.drawable.ly_flag
        "MAD" -> R.drawable.ma_flag
        "MDL" -> R.drawable.md_flag
        "MGA" -> R.drawable.mg_flag
        "MKD" -> R.drawable.mk_flag
        "MMK" -> R.drawable.mm_flag
        "MNT" -> R.drawable.mn_flag
        "MOP" -> R.drawable.mo_flag
        "MRU" -> R.drawable.mr_flag
        "MUR" -> R.drawable.mu_flag
        "MVR" -> R.drawable.mv_flag
        "MWK" -> R.drawable.mw_flag
        "MXN" -> R.drawable.mx_flag
        "MYR" -> R.drawable.my_flag
        "MZN" -> R.drawable.mz_flag
        "NAD" -> R.drawable.na_flag
        "NGN" -> R.drawable.ng_flag
        "NIO" -> R.drawable.ni_flag
        "NOK" -> R.drawable.no_flag
        "NPR" -> R.drawable.np_flag
        "NZD" -> R.drawable.nz_flag
        "OMR" -> R.drawable.om_flag
        "PAB" -> R.drawable.pa_flag
        "PEN" -> R.drawable.pe_flag
        "PGK" -> R.drawable.pg_flag
        "PHP" -> R.drawable.ph_flag
        "PKR" -> R.drawable.pk_flag
        "PLN" -> R.drawable.pl_flag
        "PYG" -> R.drawable.py_flag
        "QAR" -> R.drawable.qa_flag
        "RON" -> R.drawable.ro_flag
        "RSD" -> R.drawable.rs_flag
        "RUB" -> R.drawable.ru_flag
        "RWF" -> R.drawable.rw_flag
        "SAR" -> R.drawable.sa_flag
        "SBD" -> R.drawable.sb_flag
        "SCR" -> R.drawable.sc_flag
        "SDG" -> R.drawable.sd_flag
        "SEK" -> R.drawable.se_flag
        "SGD" -> R.drawable.sg_flag
        "SHP" -> R.drawable.sh_flag
        "SLL" -> R.drawable.sl_flag
        "SOS" -> R.drawable.so_flag
        "SRD" -> R.drawable.sr_flag
        "SSP" -> R.drawable.ss_flag
        "STN" -> R.drawable.st_flag
        "SVC" -> R.drawable.sv_flag
        "SYP" -> R.drawable.sy_flag
        "SZL" -> R.drawable.sz_flag
        "THB" -> R.drawable.th_flag
        "TJS" -> R.drawable.tj_flag
        "TMT" -> R.drawable.tm_flag
        "TND" -> R.drawable.tn_flag
        "TOP" -> R.drawable.to_flag
        "TRY" -> R.drawable.tr_flag
        "TTD" -> R.drawable.tt_flag
        "TWD" -> R.drawable.tw_flag
        "TZS" -> R.drawable.tz_flag
        "UAH" -> R.drawable.ua_flag
        "UGX" -> R.drawable.ug_flag
        "USD" -> R.drawable.us_flag
        "UYU" -> R.drawable.uy_flag
        "UZS" -> R.drawable.uz_flag
        "VES" -> R.drawable.ve_flag
        "VND" -> R.drawable.vn_flag
        "VUV" -> R.drawable.vu_flag
        "WST" -> R.drawable.ws_flag
        "YER" -> R.drawable.ye_flag
        "ZAR" -> R.drawable.za_flag
        "ZMW" -> R.drawable.zm_flag
        "ZWL" -> R.drawable.zw_flag
        else -> R.drawable.ic_refresh
    }
}